Airport-Management-System-master/airport/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    # password reset
    path('reset_password/',
         auth_views.PasswordResetView.as_view(
             template_name="handyman/forgot-password.html",
             html_email_template_name="client/emails/password-reset.html",
             subject_template_name="client/emails/password_reset_subject.txt",
         ),
         name="password_reset"),
    path('reset_password_done/',
         auth_views.PasswordResetDoneView.as_view(template_name="handyman/password-reset-done.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="handyman/reset-password.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="handyman/password-reset-complete.html"),
         name="password_reset_complete"),

    path('admin/', admin.site.urls),
    
    path('financemanager/', include(('financemanager.urls', 'financemanager'), namespace="financemanager")),
    path('handyman/', include(('handyman.urls', 'handyman'), namespace="handyman")),
    path('manager/', include(('manager.urls', 'manager'), namespace="manager")),
    path('', include(('client.urls', 'client'), namespace="client")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Airport-Management-System-master/client/urls.py
from django.urls import path

from .views import IndexView, AboutView, ContactView, ProfileView, clientLoginView, \
    clientSignUpView, VerifyEmail, log_out, Appointment_payment, appointment, faq, change_password, \
    success_page, receipts, FeedbackView, Appointment_api, cancel_Appointment, ClientServiceListView

urlpatterns = [
    path('logout/', log_out, name="logout"),
    path('verify/<uidb64>/<token>/', VerifyEmail.as_view(), name='verify'),
    path('sign-up/', clientSignUpView.as_view(), name="sign_up"),
    path('login/', clientLoginView.as_view(), name="login"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('feedback/', FeedbackView.as_view(), name="feedback"),
    path('contact/', ContactView.as_view(), name="contact"),
    path('about/', AboutView.as_view(), name="about_us"),
    path('cancel_appointment/<slug>/', cancel_Appointment, name="cancel_Appointment"),
    path('payment/<slug>/', Appointment_payment, name="payment"),
    path('Appointment_api/', Appointment_api, name="Appointment_api"),
    path('Appointment/', appointment, name="Appointment"),
    path('log_out/', log_out, name="log_out"),
    path('faq/', faq, name="faq"),
    path('ClientService/', ClientServiceListView.as_view(), name="ClientService"),
    path('change_password/', change_password, name="change_password"),
    path('success_page/<slug>/', success_page, name="success_page"),
    path('receipts/', receipts, name="receipts"),
    path('', IndexView.as_view(), name="index"),
]

Airport-Management-System-master/handyman/urls.py
from django.urls import path
#from django.contrib import admin
from .reports import Appointment_report, ClientService_report
from .views import IndexView, handymanLoginView, handymanSignUpView, LogoutView, ProfileView, \
    ChangePasswordView, FeedBackView,ClientServiceListView, AppointmentListView, ElectricianListView

urlpatterns = [
    path('ClientService-pdf/', ClientService_report, name="ClientService-pdf"),
    path('Appointment-pdf/', Appointment_report, name="Appointment-pdf"),
    path('ClientService/', ClientServiceListView.as_view(), name="ClientService"),
    path('Electrician/', ElectricianListView.as_view(), name="Electrician"),
    path('Appointment/', AppointmentListView.as_view(), name="Appointment"),
    path('login/', handymanLoginView.as_view(), name="login"),
    path('register/', handymanSignUpView.as_view(), name="register"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('change-password/', ChangePasswordView.as_view(), name="change-password"),
    path('feedback/', FeedBackView.as_view(), name="feedback"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('', IndexView.as_view(), name="index"),
]

Airport-Management-System-master/handyman/models.py
from multiprocessing.connection import Client
from django.db import models

# Create your models here.
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _
from Users.models import User, Profile, Feedback
from flights.models import service
from client.models import client


class handyman(User):
    class UserType(models.TextChoices):
        ELECTRICIAN = 'ELECTRICIAN', "ELECTRICIAN"
        PAINTERS = 'PAINTERS', "PAINTERS"
        TRANSPORTERS = 'TRANSPORTERS', "TRANSPORTERS"
        FUMIGANTS ='FUMIGANTS', "FUMIGANTS"
        


    User_type = models.CharField(max_length=250, choices=UserType.choices, default=UserType.ELECTRICIAN)

    class Meta:
        verbose_name = 'handyman'
        verbose_name_plural = 'handyman'


class handymanProfile(Profile):
    User = models.OneToOneField(handyman, on_delete=models.CASCADE)
    service = models.ForeignKey(service, on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name = 'handyman Profile'
        verbose_name_plural = 'handyman Profiles'


class handymanFeedback(Feedback):
    User = models.ForeignKey(handyman, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'handyman Feedback'
        verbose_name_plural = 'handyman Feedback'


class CheckAppointments(models.Model):
    status = models.BooleanField(default=False)
    handyman = models.ForeignKey(handyman, on_delete=models.CASCADE, null=True)
    client = models.ForeignKey(client,on_delete=models.CASCADE, null=True)
    #ticket = models.OneToOneField(Booking, on_delete=models.CASCADE, null=True)
    created = models.DateTimeField(_('Created'), auto_now_add=True, null=True)
    updated = models.DateTimeField(_('Updated'), auto_now=True, null=True)

Airport-Management-System-master/handyman/forms.py
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import ModelForm, forms

from handyman.models import handyman, handymanProfile, handymanFeedback


class handymanSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = handyman
        fields = ['last_name', 'first_name', 'email', 'username', 'User_type']

    def save(self, commit=True):
        User = super().save(commit=False)
        User.is_handyman = True
        User.is_active = False
        if commit:
            User.save()
        return User


class handymanProfileForm(ModelForm):
    class Meta:
        model = handymanProfile
        fields = ['image', 'gender', 'phone_number', 'country', 'service']


class handymanForm(ModelForm):
    class Meta:
        model = handyman
        fields = ['last_name', 'first_name', 'email']


class handymanFeedbackForm(ModelForm):
    class Meta:
        model = handymanFeedback
        fields = ['subject', 'message']


class handymanAuthenticationForm(AuthenticationForm):

    def clean(self):
        super().clean()
        if self.user_cache is not None and not self.user_cache.is_handyman:
            logout(self.request)
            raise forms.ValidationError("Sorry invalid credentials.",
                                        code='invalid login')

Airport-Management-System-master/handyman/views.py
from decimal import Context
from difflib import context_diff
from multiprocessing import context
from django.shortcuts import render

# Create your views here.

#def index(request):
    #return render(request, "index.html")
from django.contrib import messages
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import CreateView, ListView

from flights.models import Appointment, ClientService
from handyman.forms import handymanAuthenticationForm, handymanSignUpForm, handymanProfileForm, \
    handymanForm, handymanFeedbackForm
from handyman.models import handymanFeedback, handyman, CheckAppointments


class handymanLoginView(LoginView):
    template_name = "handyman/login.html"
    authentication_form = handymanAuthenticationForm

    def form_valid(self, form):
        User = form.get_user()
        if User is not None:
            login(self.request, User)
            messages.success(self.request, f"Hi {User.get_full_name}, you've logged in successfully.")
        return redirect('handyman:index')


class handymanSignUpView(CreateView):
    form_class = handymanSignUpForm
    template_name = "handyman/register.html"

    def form_valid(self, form):
        User = form.save(commit=False)
        User.save()
        messages.success(self.request, f"Hi {User.get_full_name}, your account has been created successfully wait for "
                                       f"approval.")
        return redirect('handyman:login')


class IndexView(View):
    template_name = "handyman/index.html"

    def get(self, *args, **kwargs):
        context = {}
        request = self.request
        context['Appointments_count'] = Appointment.objects.filter(service=request.user.handyman.handymanprofile.service).count()
        context['ClientService_count'] = ClientService.objects.filter(service=request.user.handyman.handymanprofile.service).count()  
        context['attendants_count'] = handyman.objects.filter(
            User_type="Electrician", handymanprofile__service=request.user.handyman.handymanprofile.service).count()        
        return render(self.request, self.template_name, context)


class ProfileView(View):
    template_name = "handyman/profile.html"

    def get(self, *args, **kwargs):
        request = self.request
        p_form = handymanProfileForm(instance=request.user.handyman.handymanprofile)
        form = handymanForm(instance=request.user.handyman)
        return render(self.request, self.template_name, {"p_form": p_form, "form": form})

    def post(self, *args, **kwargs):
        request = self.request
        p_form = handymanProfileForm(request.POST, request.FILES,
                                        instance=request.user.handyman.handymanprofile)
        form = handymanForm(request.POST, instance=request.user.handyman)
        if form.is_valid() and p_form.is_valid():
            form.save()
            instance = p_form.save(commit=False)
            # This makes sure electrician does not change Service after selecting
            if request.user.handyman.handymanprofile.service:
                instance.service = request.user.handyman.handymanprofile.service
            instance.save()
            messages.success(request, 'profile updated successfully')
        else:
            return render(request, self.template_name, {"p_form": p_form, "form": form})
        return redirect("handyman:profile")


class ChangePasswordView(View):
    template_name = "handyman/change-password.html"

    def get(self, *arg, **kwargs):
        request = self.request
        form = PasswordChangeForm(request.User)
        return render(request, self.template_name, {"form": form})

    def post(self, *args, **kwargs):
        request = self.request
        form = PasswordChangeForm(request.User, request.POST)
        if form.is_valid():
            User = form.save()
            update_session_auth_hash(request, User)  # Important!
            messages.success(request, 'Your password was successfully updated!')
        else:
            return render(request, self.template_name, {"form": form})
        return redirect("handyman:change-password")


class FeedBackView(View):
    template_name = "feedback.html"

    def get(self, *arg, **kwargs):
        request = self.request
        form = handymanFeedbackForm()
        return render(request, self.template_name, {"form": form})

    def post(self, *args, **kwargs):
        request = self.request
        form = handymanFeedbackForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.User = request.User.handyman
            if handymanFeedback.objects.filter(User=instance.User, subject=instance.subject, message=instance.message
                                                  ).exists():
                messages.info(request, f"Sorry, {instance.subject} has already been sent.")
            else:
                instance.save()
                messages.success(request, 'feedback has been sent successfully.')
        else:
            return render(request, self.template_name, {"form": form})
        return redirect("handyman:feedback")


class AppointmentListView(ListView):
    template_name = "handyman/Appointment.html"

    def get_queryset(self):
        request = self.request
        object_list = Appointment.objects.filter(ClientService=request.User.handyman.handymanprofile.ClientService)
        return object_list

    def post(self, *args, **kwargs):
        request = self.request
        check = request.POST.get('check')
        if check is not None:
            instance = get_object_or_404(Appointment, id=check)
            instance = CheckAppointments.objects.get(Appointment=instance)
            instance.status = True
            instance.save()
            messages.success(request, f"Appointment has been Checked successfully")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class ClientServiceListView(View):
    template_name = "handyman/ClientService.html"

    def get(self, *args, **kwargs):
        request = self.request
        object_list = ClientService.objects.filter(ClientService=request.User.handyman.handymanprofile.ClientService)
     #   context = {'d_form': DepartureForm(), 'a_form': ArrivalForm(), 'object_list': object_list}
        return render(self.request, self.template_name)


class ElectricianListView(ListView):
    template_name = "handyman.html"

    def get_queryset(self):
        request = self.request
        object_list = handymanProfileForm.objects.filter(
            User_type="Electrician", handymanprofile__ClientService=request.User.handyman.handymanprofile.ClientService)
        return object_list


class LogoutView(View):
    def get(self, *args, **kwargs):
        logout(self.request)
        messages.info(self.request, f"You've logged out successfully.")
        return redirect("handyman:index")

Airport-Management-System-master/handyman/templates/handyman/includes/footer.html
<!-- Footer -->
    <footer class="sticky-footer bg-white">
        <div class="container my-auto">
            <div class="copyright text-center my-auto">
                <span>Handymanservice254 &copy; {% now "Y" %}</span>
            </div>
        </div>
    </footer>
<!-- End of Footer -->

Airport-Management-System-master/handyman/templates/handyman/includes/logout-modal.html
<!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{% url 'handyman:logout' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>

Airport-Management-System-master/handyman/templates/handyman/includes/side-bar.html
<!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'handyman:index' %}">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-laugh-wink"></i>
            </div>
            <div class="sidebar-brand-text mx-3">{{request.User.handyman.get_User_type_display}} <sup>admin</sup></div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'handyman:index' %}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading">
            {{request.User.handyman.get_User_type_display}}
        </div>

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#Appointment"
                aria-expanded="true" aria-controls="Appointment">
                <i class="fas fa-fw fa-cog"></i>
                <span>Appointment</span>
            </a>
            <div id="Appointment" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Appointment:</h6>
                    <a class="collapse-item" href="{% url 'handyman:Appointment' %}">Appointment</a>
                </div>
            </div>
        </li>

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#ClientService"
                aria-expanded="true" aria-controls="ClientService">
                <i class="fas fa-fw fa-cog"></i>
                <span>ClientServices</span>
            </a>
            <div id="flights" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">ClientServices:</h6>
                    <a class="collapse-item" href="{% url 'handyman:ClientService' %}">ClientServices</a>
                </div>
            </div>
        </li>
        {% if request.User.handyman.User_type == "Electrician" %}
            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Addons
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                    aria-expanded="true" aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Electrician</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Electrician:</h6>
                        <a class="collapse-item" href="{% url 'handyman:Electrician' %}">Electrician</a>
                    </div>
                </div>
            </li>
        {% endif %}
        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

<!--        &lt;!&ndash; Sidebar Message &ndash;&gt;-->
<!--        <div class="sidebar-card d-none d-lg-flex">-->
<!--            <img class="sidebar-card-illustration mb-2" src="img/undraw_rocket.svg" alt="...">-->
<!--            <p class="text-center mb-2"><strong>SB Admin Pro</strong> is packed with premium features, components, and more!</p>-->
<!--            <a class="btn btn-success btn-sm" href="https://startbootstrap.com/theme/sb-admin-pro">Upgrade to Pro!</a>-->
<!--        </div>-->

    </ul>
    <!-- End of Sidebar -->

Airport-Management-System-master/handyman/templates/handyman/includes/top-bar.html
{% load static %}
<!-- Topbar -->
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search -->
        <form
            class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
                <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                    aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                    </button>
                </div>
            </div>
        </form>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
                <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-search fa-fw"></i>
                </a>
                <!-- Dropdown - Messages -->
                <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                    aria-labelledby="searchDropdown">
                    <form class="form-inline mr-auto w-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small"
                                placeholder="Search for..." aria-label="Search"
                                aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.User.get_full_name}}</span>
                    {% if request.User.handyman.handymanProfile.image.url %}
                        <img class="img-profile rounded-circle" src="{{request.User.handyman.handymanProfile.image.url}}">
                    {% else %}
                        <img class="img-profile rounded-circle" src="{% static 'staff/img/undraw_profile.svg' %}">
                    {% endif %}
                </a>
                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                    aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="{% url 'handyman:profile' %}">
                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                        Profile
                    </a>
                    <a class="dropdown-item" href="{% url 'handyman:change-password' %}">
                        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                        Change Password
                    </a>
                    <a class="dropdown-item" href="{% url 'handyman:feedback' %}">
                        <i class="fas fa-sms fa-sm fa-fw mr-2 text-gray-400"></i>
                        Feedback
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Logout
                    </a>
                </div>
            </li>

        </ul>

    </nav>
    <!-- End of Topbar -->