Airport-Management-System-master/airport/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    # password reset
    path('reset_password/',
         auth_views.PasswordResetView.as_view(
             template_name="handyman/forgot-password.html",
             html_email_template_name="client/emails/password-reset.html",
             subject_template_name="client/emails/password_reset_subject.txt",
         ),
         name="password_reset"),
    path('reset_password_done/',
         auth_views.PasswordResetDoneView.as_view(template_name="handyman/password-reset-done.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="handyman/reset-password.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="handyman/password-reset-complete.html"),
         name="password_reset_complete"),

    path('admin/', admin.site.urls),
    
    path('financemanager/', include(('financemanager.urls', 'financemanager'), namespace="financemanager")),
    path('handyman/', include(('handyman.urls', 'handyman'), namespace="handyman")),
    path('manager/', include(('manager.urls', 'manager'), namespace="manager")),
    path('', include(('client.urls', 'client'), namespace="client")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Airport-Management-System-master/client/urls.py
from django.urls import path

from .views import IndexView, AboutView, ContactView, ProfileView, clientLoginView, \
    clientSignUpView, VerifyEmail, log_out, Appointment_payment, appointment, faq, change_password, \
    success_page, receipts, FeedbackView, Appointment_api, cancel_Appointment, ClientServiceListView

urlpatterns = [
    path('logout/', log_out, name="logout"),
    path('verify/<uidb64>/<token>/', VerifyEmail.as_view(), name='verify'),
    path('sign-up/', clientSignUpView.as_view(), name="sign_up"),
    path('login/', clientLoginView.as_view(), name="login"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('feedback/', FeedbackView.as_view(), name="feedback"),
    path('contact/', ContactView.as_view(), name="contact"),
    path('about/', AboutView.as_view(), name="about_us"),
    path('cancel_appointment/<slug>/', cancel_Appointment, name="cancel_Appointment"),
    path('payment/<slug>/', Appointment_payment, name="payment"),
    path('Appointment_api/', Appointment_api, name="Appointment_api"),
    path('Appointment/', appointment, name="Appointment"),
    path('log_out/', log_out, name="log_out"),
    path('faq/', faq, name="faq"),
    path('ClientService/', ClientServiceListView.as_view(), name="ClientService"),
    path('change_password/', change_password, name="change_password"),
    path('success_page/<slug>/', success_page, name="success_page"),
    path('receipts/', receipts, name="receipts"),
    path('', IndexView.as_view(), name="index"),
]

Airport-Management-System-master/Users/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.forms import ReadOnlyPasswordHashField

User = get_user_model()


class UserAdminCreationForm(forms.ModelForm):
    '''A form for creating new users. Includes all required fields plus
    repeated password'''
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self): # checking that the two passwords match
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Passwords do not match')
        return password2

    def save(self, commit=True): # save he proovided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    ''' A form for updating users, includes all the fields on the user, but
    replaces the password fields with admin's password hash display field. '''

    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'is_active')

    def clean_password(self):
        ''' Regardless of what the user provides retrun the initial value.
        This is done here rather than on the field, because the field does
        not have access to the initial value. '''
        return self.initial['password']


class LoginForm(forms.Form):
    username = forms.EmailField(label='Email', widget=forms.TextInput(attrs={'class': 'form-control',
                                                                           'placeholder': 'Enter username'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                                   'placeholder': 'Enter password'}))

    def get_user(self, *args, **kwargs):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = authenticate(username=username, password=password)
        return user


class RegistrationForm(forms.ModelForm):
    '''A form for creating new users. Includes all required fields plus
    repeated password'''
    last_name = forms.CharField(label="last name", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter last name'}))
    first_name = forms.CharField(label="first name", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter first name'}))
    username = forms.CharField(label="username", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Username'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter password'}))
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm password'}))

    class Meta:
        model = User
        fields = ['email']
        widgets = {'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter Email'})}

    def clean_password2(self):  # checking that the two passwords match
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Passwords do not match')
        return password2

    def save(self, commit=True): # save he proovided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.is_active = False
            user.is_client = True
            user.save()
        return user

Airport-Management-System-master/client/views.py
from datetime import datetime
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash, logout, login
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import LoginView
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.utils.encoding import force_text, force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views import View
from django.views.generic import CreateView, ListView
from flights.models import service, ClientService, Appointment
from financemanager.forms import PaymentForm
from financemanager.models import Payment, financemanager
from client.forms import clientForm, clientProfileForm, clientSignUpForm, clientAuthenticationForm, \
    clientFeedbackForm
from client.models import client
from Users.decorators import client_required
from Users.models import User
from Users.tokens import account_activation_token
from utils.utils import generate_key
import django.utils.timezone


class clientLoginView(LoginView):
    template_name = 'accounts.html'
    authentication_form = clientAuthenticationForm

    def form_valid(self, form):
        """Security check complete. Log the user in."""
        print(form.get_user())
        login(self.request, form.get_user())
        data = {'message': 'User has logged in successfully'}
        return JsonResponse(data)

    def form_invalid(self, form):
        print(form)
        messages.error(self.request, form.non_field_errors)
        return JsonResponse({'form': form.errors}, safe=False)


class clientSignUpView(CreateView):
    form_class = clientSignUpForm
    template_name = 'client/include/accounts.html'

    def get_form_kwargs(self):
        kwargs = super(clientSignUpView, self).get_form_kwargs()
        return kwargs

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_invalid(self, form):
        return JsonResponse(form.errors)

    def form_valid(self, form):
        name = form.instance.first_name
        last = form.instance.last_name
        user = form.save(commit=False)
        user.is_active = True
        user.save()
        current_site = get_current_site(self.request)
        to_email = form.cleaned_data.get('email')
        subject = f'client Email Verification.'
        msg_plain = render_to_string('client/emails/email.txt', {'user_name': user.get_full_name, })
        msg_html = render_to_string('client/emails/account_activation_email.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': account_activation_token.make_token(user),
        })
        send_mail(subject, msg_plain, 'Handyman 254', [to_email], html_message=msg_html)
        data = {"message": f"Hi {name} {last}, your account has been created successfully verify your email."}
        return JsonResponse(data)


class VerifyEmail(View):

    def get(self, *args, **kwargs):
        uidb64 = kwargs['uidb64']
        token = kwargs['token']
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = client.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            if user.is_verified:
                messages.info(self.request, "you've already confirmed your email.")
            elif not user.is_verified:
                user.is_verified = True
                user.save()
                messages.info(self.request, "You've successfully verified your email. use your email to login")
            return redirect('client:login')
        else:
            data = {'message': 'The confirmation link was invalid, possibly because it has already been used.'}
            return JsonResponse(data)


#class IndexView(View):
    #template_name = "client/index.html"
    #def appointment(request):

    #def get(self, *args, **kwargs):
        #ClientService = ClientService.objects.filter(Day__gte=datetime())
       # ClientService = ClientService.objects.filter(Day__gte=datetime.now())
        #return render(self.request, self.template_name)
class IndexView(View):
    template_name = "client/index.html"

    def get(self, *args, **kwargs):
        global service
        global ClientService

        services = service.objects.all()
        ClientServices = ClientService.objects.filter(Day__gte=timezone.now())
        return render(self.request, self.template_name, { 'services': services,'ClientServices': ClientServices})

class AboutView(View):
    template_name = 'client/about-us.html'

    def get(self, *args, **kwargs):
        return render(self.request, self.template_name)


class ContactView(View):
    template_name = "client/contact.html"

    def get(self, *args, **kwargs):
        return render(self.request, self.template_name)


class FeedbackView(CreateView):
    form_class = clientFeedbackForm
    template_name = "client/feedback.html"

    def get_form_kwargs(self):
        kwargs = super(FeedbackView, self).get_form_kwargs()
        return kwargs

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_invalid(self, form):
        return render(self.request, self.template_name, {'form': form})

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.admin = User.objects.filter(is_handyman=True).first()
        instance.user = self.request.user.client
        instance.save()
        messages.success(self.request, 'Thank you for your feedback.')
        return redirect('client:index')


@method_decorator(client_required, name='dispatch')
class ProfileView(View):
    template_name = "client/profile.html"

    def get(self, *args, **kwargs):
        request = self.request
        p_form = clientProfileForm(instance=request.user.client.clientprofile)
        form = clientForm(instance=request.user.client)
        return render(self.request, self.template_name, {'p_form': p_form, 'form': form, })

    def post(self, *args, **kwargs):
        request = self.request
        p_form = clientProfileForm(request.POST, request.FILES, instance=request.user.client.clientprofile)
        form = clientForm(request.POST, instance=request.user.client)
        if form.is_valid() and p_form.is_valid():
            form.save()
            p_form.save()
            messages.success(request, "Your Profile has been updated!")
        return render(self.request, self.template_name, {'p_form': p_form, 'form': form, })


class ClientServiceListView(ListView):
    template_name = "client/ClientService.html"
    paginate_by = 5

    def get_queryset(self):
        object_list = ClientService.objects.filter(Day__gte=datetime.now())
        return object_list

    def post(self, *args, **kwargs):
        service = self.request.POST.get('ClientService')
        object_list = self.get_queryset().filter(service=service)
        return render(self.request, self.template_name, {'object_list': object_list})


@client_required
def Appointment_api(request):
    if request.method == "POST":
     ClientService_id = request.POST.get('Appointment_id')
    if ClientService.objects.filter(id=ClientService_id).exists():
            ClientService = ClientService.objects.get(id=ClientService_id)
            # making sure only available seats are booked
            if Appointment.objects.filter(ClientService=ClientService).count() < ClientService.seats_no:
                if Appointment.objects.filter(ClientService=ClientService, client=request.user.client).exists():
                    messages.info(request, "Appointment has already been made")
                else:
                    Appointment.objects.create(ClientService=ClientService, client=request.user.client, code=generate_key(12, 12))
                    messages.success(request, "Appointment has been booked successfully")
            else:
                messages.info(request, "Sorry all Handymen are booked")
            return redirect('client:Appointment')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@client_required
def appointment(request):
    Appointments = Appointment.objects.filter(client=request.user.client, ClientService__Day=datetime.now(),
                                      paid=False).order_by('-created')
    paid_Appointments = Appointment.objects.filter(client=request.user.client, paid=True).order_by('-created')
    return render(request, 'client/Appointment.html', {'Appointments': Appointments, 'paid_Appointments': paid_Appointments})


@client_required
def cancel_Appointment(request, slug):
    Appointment_obj = get_object_or_404(Appointment, slug=slug)
    Appointment_obj.delete()
    messages.info(request, "Apointment has been cancelled.")
    return redirect(reverse("client:index"))


@client_required
def Appointment_payment(request, slug):
    Appointment_obj = get_object_or_404(Appointment, slug=slug)
    form = PaymentForm()
    if request.method == "POST":
        form = PaymentForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.code = generate_key(11, 11)
            instance.client = Appointment_obj
            instance.client = request.user.client

Airport-Management-System-master/client/templates/client/include/accounts.html
{% load static %}
    <!-- Sign Up Window Code -->
    <div class="modal fade" id="signin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content" id="myModalLabel1">
                <div class="modal-body">
                    <div class="text-center"><img src="{% static 'client/assets/img/logo copy.png' %}" class="img-responsive" alt=""></div>

                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs nav-advance theme-bg" role="tablist">
                        <li class="nav-item active">
                            <a class="nav-link" data-toggle="tab" href="#login" role="tab">
                            <i class="ti-user"></i> Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#register" role="tab">
                            <i class="ti-user"></i> Register</a>
                        </li>
                    </ul>
                    <!-- Nav tabs -->

                    <!-- Tab panels -->
                    <div class="tab-content">

                        <!-- Employer Panel 1-->
                        <div class="tab-pane fade in show active" id="login" role="tabpanel">
                            <p class="text-danger" id="form-errors"></p>
                            <form method="post" action="{% url 'client:login' %}" id="client-login">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label>User Name</label>
                                    <input type="text" class="form-control" name="username" placeholder="User Name" required>
                                    <div class="text-danger" id="error-username"></div>
                                </div>

                                <div class="form-group">
                                    <label>Password</label>
                                    <input type="password" class="form-control" name="password" id="id_password" placeholder="*********" required>
                                    <div class="text-danger" id="error-password"></div>
                                </div>

                                <div class="form-group">
                                    <span class="custom-checkbox">
                                        <input type="checkbox" id="4">
                                        <label for="4"></label>Remember me
                                    </span>
                                    <a href="{% url 'password_reset' %}" title="Forget" class="fl-right">Forgot Password?</a>
                                </div>
                                <div class="form-group text-center">
                                    <button type="submit" class="btn theme-btn full-width btn-m" id="client-login-btn">Login </button>
                                </div>

                            </form>

                        </div>
                        <!--/.Panel 1-->

                        <!-- Candidate Panel 2-->
                        <div class="tab-pane fade" id="register" role="tabpanel">
                            <form method="post" action="{% url 'client:sign_up' %}" id="client-register">
                                {% csrf_token %}

                                <div class="form-group">
                                    <label>First Name</label>
                                    <input type="text" class="form-control" name="first_name" id="id_first_name" placeholder="First Name" required>
                                    <div class="text-danger" id="error_first_name"></div>
                                </div>

                                <div class="form-group">
                                    <label>Last Name</label>
                                    <input type="text" class="form-control" name="last_name" id="id_last_name" placeholder="Last Name" required>
                                    <div class="text-danger" id="error_last_name"></div>
                                </div>

                                <div class="form-group">
                                    <label>User Name</label>
                                    <input type="text" class="form-control" name="username" id="id_username" placeholder="User Name" required>
                                    <div class="text-danger" id="error_username"></div>
                                </div>

                                <div class="form-group">
                                    <label>Email Address</label>
                                    <input type="email" class="form-control" name="email" id="id_email" placeholder="Email Address" required>
                                    <div class="text-danger" id="error_email"></div>
                                </div>

                                <div class="form-group">
                                    <label>Password</label>
                                    <input type="password" class="form-control" name="password1" id="id_password1" placeholder="*********" required>
                                    <div class="text-danger" id="error_password1"></div>
                                </div>

                                <div class="form-group">
                                    <label>Confirm Password</label>
                                    <input type="password" class="form-control" name="password2" id="id_password2" placeholder="*********" required>
                                    <div class="text-danger" id="error_password2"></div>
                                </div>

                                <div class="form-group text-center">
                                    <button type="submit" class="btn theme-btn full-width btn-m" id="client-register-btn">Register </button>
                                </div>

                            </form>

                        </div>
                        <!--/.Panel 2-->

                    </div>
                    <!-- Tab panels -->
                </div>
            </div>
        </div>
    </div>
    <!-- End Sign Up Window -->

Airport-Management-System-master/client/templates/client/include/before-footer.html
<!-- ============== Before Footer ====================== -->
		<section class="before-footer bt-1 bb-1">
			<div class="container-fluid padd-0 full-width">

				<div class=" col-md-2 col-sm-2 br-1 mbb-1">
					<div class="data-flex">
						<h4>Contact Us!</h4>
					</div>
				</div>

				<div class="col-md-3 col-sm-3 br-1 mbb-1">
					<div class="data-flex text-center">
					Meru, Kenya
					</div>
				</div>

				<div class="col-md-3 col-sm-3 br-1 mbb-1">
					<div class="data-flex text-center">
						<span class="d-block mrg-bot-0">0702555666</span>
						<a href="#" class="theme-cl"><strong>info@handymancom</strong></a>
					</div>
				</div>

				<div class="col-md-4 col-sm-4 padd-0">
					<div class="data-flex padd-0">
						<ul class="social-share">
							<li><a href="#"><i class="fa fa-facebook theme-cl"></i></a></li>
							<li><a href="#"><i class="fa fa-google-plus theme-cl"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter theme-cl"></i></a></li>
							<li><a href="#"><i class="fa fa-linkedin theme-cl"></i></a></li>
						</ul>
					</div>
				</div>

			</div>
		</section>
		<!-- =================== Before Footer ====================== -->

Airport-Management-System-master/client/templates/client/include/footer.html
		<!-- ================= footer start ========================= -->
		<footer class="footer dark-bg">
			<div class="container">

				<!-- Row Start -->
				<div class="row">

					<div class="col-md-8 col-sm-8">
						<div class="row">
							<div class="col-md-4 col-sm-4">
								<h4>Other Accounts</h4>
								<ul>
									<li><a href="{% url 'handyman:index' %}">handyman</a></li>
<!--									<li><a href="#">Security</a></li>-->
<!--									<li><a href="#">Attendant</a></li>-->
									<li><a href="{% url 'financemanager:index' %}">Financemanager</a></li>
									<li><a href="{% url 'manager:index' %}">manager</a></li>
								</ul>
							</div>
							<div class="col-md-4 col-sm-4">
								<h4>Other Features</h4>
								<ul>
									<li><a href="#">Dashboard</a></li>
								</ul>
							</div>
							<div class="col-md-4 col-sm-4">
								<h4>Help</h4>
								<ul>
									<li><a href="{% url 'client:faq' %}">FAQs</a></li>
									<li><a href="{% url 'client:about_us' %}">About Us</a></li>
									<li><a href="{% url 'client:contact' %}">Contact</a></li>
									{% if request.user.is_authenticated and request.user.is_client %}
										<li><a href="{% url 'client:feedback' %}">Feedback</a></li>
									{% endif %}

								</ul>
							</div>
						</div>
					</div>

					<div class="col-md-4 col-sm-4">
						<h4>Subscribe Now</h4>
						<!-- Newsletter -->
						<div class="input-group">
							<input type="text" class="form-control" placeholder="Enter Email">
							<span class="input-group-btn">
								<button type="button" class="btn btn-default"><i class="fa fa-location-arrow font-20"></i></button>
							</span>
						</div>

						<!-- Social Box -->
						<div class="f-social-box">
							<ul>
								<li><a href="#"><i class="fa fa-facebook facebook-cl"></i></a></li>
								<li><a href="#"><i class="fa fa-google google-plus-cl"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter twitter-cl"></i></a></li>
								<li><a href="#"><i class="fa fa-pinterest pinterest-cl"></i></a></li>
								<li><a href="#"><i class="fa fa-instagram instagram-cl"></i></a></li>
							</ul>
						</div>

<!--						&lt;!&ndash; App Links &ndash;&gt;-->
<!--						<div class="f-app-box">-->
<!--							<ul>-->
<!--								<li><a href="#"><i class="fa fa-apple"></i>App Store</a></li>-->
<!--								<li><a href="#"><i class="fa fa-android"></i>Play Store</a></li>-->
<!--							</ul>-->
<!--						</div>-->

					</div>

				</div>

				<!-- Row Start -->
				<div class="row">
					<div class="col-md-12">
						<div class="copyright text-center">
							<p><a target="_blank" href="#">Sof-smart dev</a></p>
						</div>
					</div>
				</div>

			</div>
		</footer>

Airport-Management-System-master/client/templates/client/include/navbar.html
{% load static %}
<!-- ======================= Start Navigation ===================== -->
		<nav class="navbar navbar-default navbar-mobile navbar-fixed light bootsnav">
			<div class="container">

				<!-- Start Logo Header Navigation -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
						<i class="fa fa-bars"></i>
					</button>
					<a class="navbar-brand" href="{% url 'client:index' %}">
						<img src="{% static 'client/assets/img/logo.png' %}" class="logo logo-display" alt="">
						<img src="{% static 'client/assets/img/logo.png' %}" class="logo logo-scrolled" alt="">
					</a>

				</div>
				<!-- End Logo Header Navigation -->

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="navbar-menu">

					<ul class="nav navbar-nav navbar-left" data-in="fadeInDown" data-out="fadeOutUp">

						<li class="dropdown">
							<a href="{% url 'client:index' %}">Home</a>
						</li>
						{% if request.user.is_authenticated and request.user.is_client %}
							<li>
								<a href="{% url 'client:Appointment' %}">appointment</a>
							</li>
							<li>
								<a href="{% url 'client:profile' %}">profile</a>
							</li>
							<li>
								<a href="{% url 'client:change_password' %}">change password</a>
							</li>
						{% endif %}

					</ul>

					<ul class="nav navbar-nav navbar-right">
						{% if request.user.is_authenticated and request.user.is_client %}
							<li class="br-right"><a href="{% url 'client:log_out' %}"><i class="login-icon ti-lock"></i>Logout</a></li>
						{% else %}
							<li class="br-right"><a href="javascript:void(0)"  data-toggle="modal" data-target="#signin"><i class="login-icon ti-user"></i>Login</a></li>
						{% endif %}
						{% if request.user.is_authenticated and request.user.is_client %}
							<li class="sign-up"><a class="btn-signup red-btn" href="{% url 'client:Appointment' %}"><span class="ti-briefcase"></span>appointment</a></li>
						{% endif %}
						<li class="br-right"><a href="{% url 'financemanager:index' %}"><i class="login-icon ti-user"></i>financemanager</a></li>
						<li class="br-right"><a href="{% url 'handyman:index' %}"><i class="login-icon ti-user"></i>handyman</a></li>
						<li class="br-right"><a href="{% url 'manager:index' %}"><i class="login-icon ti-user"></i>manager</a></li>
						
					</ul>

				</div>
				<!-- /.navbar-collapse -->
			</div>
		</nav>
		<!-- ======================= End Navigation ===================== -->