Airport-Management-System-master/airport/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    # password reset
    path('reset_password/',
         auth_views.PasswordResetView.as_view(
             template_name="handyman/forgot-password.html",
             html_email_template_name="client/emails/password-reset.html",
             subject_template_name="client/emails/password_reset_subject.txt",
         ),
         name="password_reset"),
    path('reset_password_done/',
         auth_views.PasswordResetDoneView.as_view(template_name="handyman/password-reset-done.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="handyman/reset-password.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="handyman/password-reset-complete.html"),
         name="password_reset_complete"),

    path('admin/', admin.site.urls),
    
    path('financemanager/', include(('financemanager.urls', 'financemanager'), namespace="financemanager")),
    path('handyman/', include(('handyman.urls', 'handyman'), namespace="handyman")),
    path('manager/', include(('manager.urls', 'manager'), namespace="manager")),
    path('', include(('client.urls', 'client'), namespace="client")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Airport-Management-System-master/client/urls.py
from django.urls import path

from .views import IndexView, AboutView, ContactView, ProfileView, clientLoginView, \
    clientSignUpView, VerifyEmail, log_out, Appointment_payment, appointment, faq, change_password, \
    success_page, receipts, FeedbackView, Appointment_api, cancel_Appointment, ClientServiceListView

urlpatterns = [
    path('logout/', log_out, name="logout"),
    path('verify/<uidb64>/<token>/', VerifyEmail.as_view(), name='verify'),
    path('sign-up/', clientSignUpView.as_view(), name="sign_up"),
    path('login/', clientLoginView.as_view(), name="login"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('feedback/', FeedbackView.as_view(), name="feedback"),
    path('contact/', ContactView.as_view(), name="contact"),
    path('about/', AboutView.as_view(), name="about_us"),
    path('cancel_appointment/<slug>/', cancel_Appointment, name="cancel_Appointment"),
    path('payment/<slug>/', Appointment_payment, name="payment"),
    path('Appointment_api/', Appointment_api, name="Appointment_api"),
    path('Appointment/', appointment, name="Appointment"),
    path('log_out/', log_out, name="log_out"),
    path('faq/', faq, name="faq"),
    path('ClientService/', ClientServiceListView.as_view(), name="ClientService"),
    path('change_password/', change_password, name="change_password"),
    path('success_page/<slug>/', success_page, name="success_page"),
    path('receipts/', receipts, name="receipts"),
    path('', IndexView.as_view(), name="index"),
]

Airport-Management-System-master/financemanager/urls.py
from django.urls import path

from financemanager.reports import payments_report
from financemanager.views import financemanagerLoginView, LogoutView, FeedBackView, ChangePasswordView, ProfileView, \
    financemanagerSignUpView, HomeView, PaymentListView

urlpatterns = [
    path('payments-pdf/', payments_report, name="payments-pdf"),
    path('payments/', PaymentListView.as_view(), name="payments"),
    path('login/', financemanagerLoginView.as_view(), name="login"),
    path('register/', financemanagerSignUpView.as_view(), name="register"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('change-password/', ChangePasswordView.as_view(), name="change-password"),
    path('feedback/', FeedBackView.as_view(), name="feedback"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('', HomeView.as_view(), name="index"),

]

Airport-Management-System-master/financemanager/models.py
from autoslug import AutoSlugField
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _
from djmoney.models.fields import MoneyField
from flights.models import Appointment
from client.models import client
from Users.models import User, Profile, Feedback


class financemanager(User):
    pass

    class Meta:
        verbose_name = 'financemanager'
        verbose_name_plural = 'Financesmanagers'


class financemanagerProfile(Profile):
    User = models.OneToOneField(financemanager, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'financemanager Profile'
        verbose_name_plural = 'financemanagers Profile'


class financemanagerFeedback(Feedback):
    User = models.ForeignKey(financemanager, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'financemanager Feedback'
        verbose_name_plural = 'financemanager Feedback'


class Payment(models.Model):
    slug = AutoSlugField(populate_from='code')
    code = models.CharField(max_length=20)
    Appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE)
    client = models.ForeignKey(client, on_delete=models.CASCADE, null=True)
    amount = MoneyField(max_digits=14, decimal_places=2, default_currency='KES')
    mpesa = models.CharField(max_length=100, help_text="This is the M-Pesa Code for the transaction")
    financemanager = models.ForeignKey(financemanager, on_delete=models.CASCADE, help_text="Financemanager", null=True)
    is_confirmed = models.BooleanField(default=False)
    updated = models.DateTimeField(_('Updated'), auto_now=True, null=True)
    created = models.DateTimeField(_('Created'), auto_now_add=True, null=True)

Airport-Management-System-master/financemanager/forms.py
from django.contrib.auth import logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.exceptions import ValidationError
from django.forms import ModelForm, forms

from financemanager.models import financemanagerProfile, financemanager, Payment, financemanagerFeedback


class financemanagerSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = financemanager
        fields = ['last_name', 'first_name', 'email', 'username']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_financemanager = True
        user.is_active = False
        if commit:
            user.save()
        return user


class financemanagerProfileForm(ModelForm):
    class Meta:
        model = financemanagerProfile
        fields = ['image', 'gender', 'phone_number', 'country']


class financemanagerForm(ModelForm):
    class Meta:
        model = financemanager
        fields = ['last_name', 'first_name', 'email']


class PaymentForm(ModelForm):
    class Meta:
        model = Payment
        fields = ['mpesa', ]

    def clean_mpesa(self):
        mpesa = self.cleaned_data.get('mpesa')
        if len(mpesa) != 10:
            raise ValidationError("Mpesa code is invalid, please confirm")
        return mpesa


class financemanagerFeedbackForm(ModelForm):
    class Meta:
        model = financemanagerFeedback
        fields = ['subject', 'message']


class financemanagerAuthenticationForm(AuthenticationForm):

    def clean(self):
        super().clean()
        if self.user_cache is not None and not self.user_cache.is_financemanager:
            logout(self.request)
            raise forms.ValidationError('Invalid username or password', code='invalid login')

Airport-Management-System-master/financemanager/views.py
from django.contrib import messages
from django.contrib.auth import login, update_session_auth_hash, logout
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import CreateView, ListView

from financemanager.forms import financemanagerAuthenticationForm, financemanagerFeedbackForm, financemanagerProfileForm, financemanagerForm, \
    financemanagerSignUpForm
from financemanager.models import financemanagerFeedback, Payment


class financemanagerLoginView(LoginView):
    template_name = "financemanager/login.html"
    authentication_form = financemanagerAuthenticationForm

    def form_valid(self, form):
        User = form.get_user()
        if User is not None:
            login(self.request, User)
            messages.success(self.request, f"Hi {User.get_full_name}, you've logged in successfully.")
        return redirect('financemanager:index')


class financemanagerSignUpView(CreateView):
    form_class = financemanagerSignUpForm
    template_name = "financemanager/register.html"

    def form_valid(self, form):
        User = form.save(commit=False)
        User.save()
        messages.success(self.request, f"Hi {User.get_full_name}, your account has been created successfully wait for "
                                       f"approval.")
        return redirect('financemanager:login')


class HomeView(View): 
    template_name = "financemanager/index.html"

    def get(self, *args, **kwargs):
        request = self.request
        context = {"pending_payments_count": Payment.objects.filter(financemanager=request.user.financemanager, is_confirmed=False),
                   "confirmed_payments_count": Payment.objects.filter(financemanager=request.user.financemanager, is_confirmed=True)}
        return render(self.request, self.template_name, context)


class ProfileView(View):
    template_name = "financemanager/profile.html"

    def get(self, *args, **kwargs):
        request = self.request
        p_form = financemanagerProfileForm(instance=request.User.financemanager.financemanagerprofile)
        form = financemanagerForm(instance=request.User.financemanager)
        return render(self.request, self.template_name, {"p_form": p_form, "form": form})

    def post(self, *args, **kwargs):
        request = self.request
        p_form = financemanagerProfileForm(request.POST, request.FILES,
                                    instance=request.User.financemanager.financemanagerprofile)
        form = financemanagerForm(request.POST, instance=request.User.financemanager)
        if form.is_valid() and p_form.is_valid():
            form.save()
            p_form.save()
            messages.success(request, 'profile updated successfully')
        else:
            return render(request, self.template_name, {"p_form": p_form, "form": form})
        return redirect("financemanager:profile")


class ChangePasswordView(View):
    template_name = "financemanager/change-password.html"

    def get(self, *arg, **kwargs):
        request = self.request
        form = PasswordChangeForm(request.User)
        return render(request, self.template_name, {"form": form})

    def post(self, *args, **kwargs):
        request = self.request
        form = PasswordChangeForm(request.User, request.POST)
        if form.is_valid():
            User = form.save()
            update_session_auth_hash(request, User)  # Important!
            messages.success(request, 'Your password was successfully updated!')
        else:
            return render(request, self.template_name, {"form": form})
        return redirect("financemanager:change-password")


class FeedBackView(View):
    template_name = "financemanager/feedback.html"

    def get(self, *arg, **kwargs):
        request = self.request
        form = financemanagerFeedbackForm()
        return render(request, self.template_name, {"form": form})

    def post(self, *args, **kwargs):
        request = self.request
        form = financemanagerFeedbackForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.User = request.User.financemanager
            if financemanagerFeedback.objects.filter(User=instance.User, subject=instance.subject, message=instance.message
                                              ).exists():
                messages.info(request, f"Sorry, {instance.subject} has already been sent.")
            else:
                instance.save()
                messages.success(request, 'feedback has been sent successfully.')
        else:
            return render(request, self.template_name, {"form": form})
        return redirect("financemanager:feedback")


class PaymentListView(ListView):
    template_name = "financemanager/payments.html"

    def get_queryset(self):
        request = self.request
        object_list = Payment.objects.filter(financemanager=request.user.financemanager)
        return object_list

    def post(self, *args, **kwargs):
        request = self.request
        confirm = request.POST.get('confirm')
        if confirm is not None:
            instance = get_object_or_404(Payment, id=confirm)
            instance.is_confirmed = True
            instance.save()
            Appointment = instance.Appointment
            Appointment.paid = True
            Appointment.save()
            messages.success(request, f"Payment has been confirmed successfully")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class LogoutView(View):
    def get(self, *args, **kwargs):
        logout(self.request)
        messages.info(self.request, f"You've logged out successfully.")
        return redirect("financemanager:index")

Airport-Management-System-master/financemanager/templates/financemanager/change-password.html
{% extends 'financemanager/layouts/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %} Change Password {% endblock %}
{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-4 text-gray-800">Change Password</h1>

        <div class="row">

            <div class="col-lg-12">
                <!-- Circle Buttons -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Change Password</h6>
                    </div>
                    <div class="card-body">
                        <form class="user" method="post" action=".">
                            {% csrf_token %}
                            {% if form.non_field_errors %} {% for error in form.non_field_errors %}
                              <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                            <div class="form-group">
                                {% render_field form.old_password class+="form-control form-control-user" placeholder="Current Password" %}
                                <div class="text-danger">{{form.errors.old_password}}</div>
                            </div>
                            <div class="form-group">
                                {% render_field form.new_password1 class+="form-control form-control-user" placeholder="New Password" %}
                                <div class="text-danger">{{form.errors.new_password1}}</div>
                            </div>
                            <div class="form-group">
                                {% render_field form.new_password2 class+="form-control form-control-user" placeholder="confirm New Password" %}
                                <div class="text-danger">{{form.errors.new_password2}}</div>
                            </div>
                            <button class="btn btn-primary btn-user btn-block" type="submit">
                                Change Password
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
{% endblock %}

Airport-Management-System-master/financemanager/templates/financemanager/feedback.html
{% extends 'financemanager/layouts/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %} Feedback {% endblock %}
{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-4 text-gray-800">Feedback</h1>

        <div class="row">

            <div class="col-lg-12">
                <!-- Circle Buttons -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Feedback</h6>
                    </div>
                    <div class="card-body">
                        <form class="user" method="post" action=".">
                            {% csrf_token %}
                            {% if form.non_field_errors %} {% for error in form.non_field_errors %}
                              <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                            <div class="form-group">
                                {% render_field form.subject class+="form-control" placeholder="Subject" %}
                                <div class="text-danger">{{form.errors.subject}}</div>
                            </div>
                            <div class="form-group">
                                {% render_field form.message class+="form-control" placeholder="type message here...." %}
                                <div class="text-danger">{{form.errors.message}}</div>
                            </div>
                            <button class="btn btn-primary btn-user btn-block" type="submit">
                                Send
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
{% endblock %}

Airport-Management-System-master/financemanager/templates/financemanager/index.html
{% extends 'financemanager/layouts/base.html' %}
{% load static %}
{% block title %} Index {% endblock %}
{% block content %}
<!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
            <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                    class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
        </div>

        <!-- Content Row -->
        <div class="row">

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                    Pending Payments</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{pending_payments_count}}</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-calendar fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-success shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                    Confirmed Payments</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{confirmed_payments_count}}</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
{% endblock %}

Airport-Management-System-master/financemanager/templates/financemanager/login.html
{% extends 'financemanager/layouts/base-auth.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}{% endblock %}
{% block content %}
<!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">financemanager/h1>
                                    </div>
                                    <form class="user" method="post" action=".">
                                        {% csrf_token %}
                                        {% if form.non_field_errors %} {% for error in form.non_field_errors %}
                                              <span class="text-danger">{{ error }}</span>
                                          {% endfor %}
                                          {% endif %}
                                        <div class="form-group">
                                            {% render_field form.username class+="form-control form-control-user" placeholder="Username" %}
                                            <div class="text-danger">{{form.errors.username}}</div>
                                        </div>
                                        <div class="form-group">
                                            {% render_field form.password class+="form-control form-control-user" placeholder="Password" %}
                                            <div class="text-danger">{{form.errors.password}}</div>
                                        </div>
<!--                                        <div class="form-group">-->
<!--                                            <div class="custom-control custom-checkbox small">-->
<!--                                                <input type="checkbox" class="custom-control-input" id="customCheck">-->
<!--                                                <label class="custom-control-label" for="customCheck">Remember-->
<!--                                                    Me</label>-->
<!--                                            </div>-->
<!--                                        </div>-->
                                        <button class="btn btn-primary btn-user btn-block" type="submit">
                                            Login
                                        </button>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'password_reset' %}">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'financemanager:register' %}">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
{% endblock %}

Airport-Management-System-master/financemanager/templates/financemanager/payments.html
{% extends 'financemanager/layouts/base.html' %}
{% load static %}
{% block title %} Payments {% endblock %}
{% block content %}

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Payments</h1>
                        <a href="{% url 'financemanager:payments-pdf' %}" class="d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                                class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
                    </div>

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Payments</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Appointment</th>
                                            <th>client</th>
                                            <th>amount</th>
                                            <th>mpesa</th>
                                            <th>Status</th>
                                            <th>Date</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Appointment</th>
                                            <th>client</th>
                                            <th>amount</th>
                                            <th>mpesa</th>
                                            <th>Status</th>
                                            <th>Date</th>
                                            <th>Action</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        {% for object in object_list %}
                                            <tr>
                                                <td>{{object.Appointment}}</td>
                                                <td>{{object.cliengt.get_full_name}}</td>
                                                <td>{{object.amount}}</td>
                                                <td>{{object.mpesa}}</td>
                                                <td>{% if object.is_confirmed %} Confirmed {% else %} pending {% endif %}</td>
                                                <td>{{object.created}}</td>
                                                <td>
                                                    {% if object.is_confirmed %}
                                                            Confirmed
                                                    {% else %}
                                                        <form method="post">
                                                            {% csrf_token %}
                                                            <button class="btn btn-success btn-sm" name="confirm" value="{{object.id}}">
                                                                <i class="zmdi zmdi-badge-check"></i>
                                                            </button>
                                                        </form>
                                                    {% endif %}
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

{% endblock %}
    {% block scripts %}
        <!-- Bootstrap core JavaScript-->
        <script src="{% static 'staff/vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'staff/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

        <!-- Core plugin JavaScript-->
        <script src="{% static 'staff/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

        <!-- Custom scripts for all pages-->
        <script src="{% static 'staff/js/sb-admin-2.min.js' %}"></script>

        <!-- Page level plugins -->
        <script src="{% static 'staff/vendor/datatables/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'staff/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

        <!-- Page level custom scripts -->
        <script src="{% static 'staff/js/demo/datatables-demo.js' %}"></script>
    {% endblock %}