Airport-Management-System-master/airport/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    # password reset
    path('reset_password/',
         auth_views.PasswordResetView.as_view(
             template_name="handyman/forgot-password.html",
             html_email_template_name="client/emails/password-reset.html",
             subject_template_name="client/emails/password_reset_subject.txt",
         ),
         name="password_reset"),
    path('reset_password_done/',
         auth_views.PasswordResetDoneView.as_view(template_name="handyman/password-reset-done.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="handyman/reset-password.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="handyman/password-reset-complete.html"),
         name="password_reset_complete"),

    path('admin/', admin.site.urls),
    
    path('financemanager/', include(('financemanager.urls', 'financemanager'), namespace="financemanager")),
    path('handyman/', include(('handyman.urls', 'handyman'), namespace="handyman")),
    path('manager/', include(('manager.urls', 'manager'), namespace="manager")),
    path('', include(('client.urls', 'client'), namespace="client")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Airport-Management-System-master/client/urls.py
from django.urls import path

from .views import IndexView, AboutView, ContactView, ProfileView, clientLoginView, \
    clientSignUpView, VerifyEmail, log_out, Appointment_payment, appointment, faq, change_password, \
    success_page, receipts, FeedbackView, Appointment_api, cancel_Appointment, ClientServiceListView

urlpatterns = [
    path('logout/', log_out, name="logout"),
    path('verify/<uidb64>/<token>/', VerifyEmail.as_view(), name='verify'),
    path('sign-up/', clientSignUpView.as_view(), name="sign_up"),
    path('login/', clientLoginView.as_view(), name="login"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('feedback/', FeedbackView.as_view(), name="feedback"),
    path('contact/', ContactView.as_view(), name="contact"),
    path('about/', AboutView.as_view(), name="about_us"),
    path('cancel_appointment/<slug>/', cancel_Appointment, name="cancel_Appointment"),
    path('payment/<slug>/', Appointment_payment, name="payment"),
    path('Appointment_api/', Appointment_api, name="Appointment_api"),
    path('Appointment/', appointment, name="Appointment"),
    path('log_out/', log_out, name="log_out"),
    path('faq/', faq, name="faq"),
    path('ClientService/', ClientServiceListView.as_view(), name="ClientService"),
    path('change_password/', change_password, name="change_password"),
    path('success_page/<slug>/', success_page, name="success_page"),
    path('receipts/', receipts, name="receipts"),
    path('', IndexView.as_view(), name="index"),
]

Airport-Management-System-master/manager/urls.py
from django.urls import path

#from manager.reports import served_report
from manager.views import managerLoginView, LogoutView, FeedBackView, ChangePasswordView, ProfileView, \
    managerSignUpView, HomeView, servedListView 

urlpatterns = [
   # path('served-pdf/', served_report, name="served-pdf"),
    path('served/', servedListView.as_view(), name="served"),
    path('login/', managerLoginView.as_view(), name="login"),
    path('register/', managerSignUpView.as_view(), name="register"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('change-password/', ChangePasswordView.as_view(), name="change-password"),
    path('feedback/', FeedBackView.as_view(), name="feedback"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('', HomeView.as_view(), name="index"),

]

Airport-Management-System-master/manager/models.py
from autoslug import AutoSlugField
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _
from djmoney.models.fields import MoneyField
from flights.models import Appointment
from client.models import client
from financemanager.models import Payment
from Users.models import User, Profile, Feedback


class manager(User):
    pass

    class Meta:
        verbose_name = 'manager'
        verbose_name_plural = 'managers'


class managerProfile(Profile):
    User = models.OneToOneField(manager, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'manager Profile'
        verbose_name_plural = 'managers Profile'


class managerFeedback(Feedback):
    User = models.ForeignKey(manager, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'manager Feedback'
        verbose_name_plural = 'manager Feedback'


class served(models.Model):
    Appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE)
    client = models.ForeignKey(client, on_delete=models.CASCADE, null=True)
    manager = models.ForeignKey(manager, on_delete=models.CASCADE, help_text="management officer", null=True)
    Payment = models.ForeignKey(Payment, on_delete=models.CASCADE, null=True)
    is_confirmed = models.BooleanField(default=False)
    updated = models.DateTimeField(_('Updated'), auto_now=True, null=True)
    created = models.DateTimeField(_('Created'), auto_now_add=True, null=True)

Airport-Management-System-master/manager/forms.py
from django.contrib.auth import logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.exceptions import ValidationError
from django.forms import ModelForm, forms

from manager.models import managerProfile, manager, Payment, managerFeedback


class managerSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = manager
        fields = ['last_name', 'first_name', 'email', 'username']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_manager = True
        user.is_active = False
        if commit:
            user.save()
        return user


class managerProfileForm(ModelForm):
    class Meta:
        model = managerProfile
        fields = ['image', 'gender', 'phone_number', 'country']


class managerForm(ModelForm):
    class Meta:
        model = manager
        fields = ['last_name', 'first_name', 'email']




class managerFeedbackForm(ModelForm):
    class Meta:
        model = managerFeedback
        fields = ['subject', 'message']


class managerAuthenticationForm(AuthenticationForm):

    def clean(self):
        super().clean()
        if self.user_cache is not None and not self.user_cache.is_manager:
            logout(self.request)
            raise forms.ValidationError('Invalid username or password', code='invalid login')

Airport-Management-System-master/manager/views.py
from django.contrib import messages
from django.contrib.auth import login, update_session_auth_hash, logout
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import CreateView, ListView

from manager.forms import managerAuthenticationForm, managerFeedbackForm, managerProfileForm, managerForm, \
managerSignUpForm
from manager.models import managerFeedback, served


class managerLoginView(LoginView):
    template_name = "manager/login.html"
    authentication_form = managerAuthenticationForm

    def form_valid(self, form):
        User = form.get_user()
        if User is not None:
            login(self.request, User)
            messages.success(self.request, f"Hi {User.get_full_name}, you've logged in successfully.")
        return redirect('manager:index')


class managerSignUpView(CreateView):
    form_class = managerSignUpForm
    template_name = "manager/register.html"

    def form_valid(self, form):
        User = form.save(commit=False)
        User.save()
        messages.success(self.request, f"Hi {User.get_full_name}, your account has been created successfully wait for "
                                       f"approval.")
        return redirect('manager:login')


class HomeView(View): 
    template_name = "manager/index.html"

    def get(self, *args, **kwargs):
        request = self.request
        context = {"pending_served_count": served.objects.filter(manager=request.user.manager, is_confirmed=False),
                   "confirmed_served_count": served.objects.filter(manager=request.user.manager, is_confirmed=True)}
        return render(self.request, self.template_name, context)


class ProfileView(View):
    template_name = "manager/profile.html"

    def get(self, *args, **kwargs):
        request = self.request
        p_form = managerProfileForm(instance=request.user.manager.managerProfile)
        form = managerForm(instance=request.User.manager)
        return render(self.request, self.template_name, {"p_form": p_form, "form": form})

    def post(self, *args, **kwargs):
        request = self.request
        p_form = managerProfileForm(request.POST, request.FILES,
                                    instance=request.User.manager.managerprofile)
        form = managerForm(request.POST, instance=request.User.manager)
        if form.is_valid() and p_form.is_valid():
            form.save()
            p_form.save()
            messages.success(request, 'profile updated successfully')
        else:
            return render(request, self.template_name, {"p_form": p_form, "form": form})
        return redirect("manager:profile")


class ChangePasswordView(View):
    template_name = "manager/change-password.html"

    def get(self, *arg, **kwargs):
        request = self.request
        form = PasswordChangeForm(request.User)
        return render(request, self.template_name, {"form": form})

    def post(self, *args, **kwargs):
        request = self.request
        form = PasswordChangeForm(request.User, request.POST)
        if form.is_valid():
            User = form.save()
            update_session_auth_hash(request, User)  # Important!
            messages.success(request, 'Your password was successfully updated!')
        else:
            return render(request, self.template_name, {"form": form})
        return redirect("manager:change-password")


class FeedBackView(View):
    template_name = "manager/feedback.html"

    def get(self, *arg, **kwargs):
        request = self.request
        form = managerFeedbackForm()
        return render(request, self.template_name, {"form": form})

    def post(self, *args, **kwargs):
        request = self.request
        form = managerFeedbackForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.User = request.User.manager
            if managerFeedback.objects.filter(User=instance.User, subject=instance.subject, message=instance.message
                                              ).exists():
                messages.info(request, f"Sorry, {instance.subject} has already been sent.")
            else:
                instance.save()
                messages.success(request, 'feedback has been sent successfully.')
        else:
            return render(request, self.template_name, {"form": form})
        return redirect("manager:feedback")


class servedListView(ListView):
    template_name = "manager/served.html"

    def get_queryset(self):
        request = self.request
        object_list = served.objects.filter(manager=request.user.manager)
        return object_list

    def post(self, *args, **kwargs):
        request = self.request
        confirm = request.POST.get('confirm')
        if confirm is not None:
            instance = get_object_or_404(served, id=confirm)
            instance.is_confirmed = True
            instance.save()
            Appointment = instance.Appointment
            Appointment.paid = True
            Appointment.save()
            messages.success(request, f"client has been successfully served")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class LogoutView(View):
    def get(self, *args, **kwargs):
        logout(self.request)
        messages.info(self.request, f"You've logged out successfully.")
        return redirect("manager:index")

Airport-Management-System-master/manager/templates/manager/includes/footer.html
<!-- Footer -->
    <footer class="sticky-footer bg-white">
        <div class="container my-auto">
            <div class="copyright text-center my-auto">
                <span>handymanservice254 &copy; {% now "Y" %}</span>
            </div>
        </div>
    </footer>
<!-- End of Footer -->

Airport-Management-System-master/manager/templates/manager/includes/logout-modal.html
<!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{% url 'manager:logout' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>

Airport-Management-System-master/manager/templates/manager/includes/side-bar.html
<!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'manager:index' %}">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-laugh-wink"></i>
            </div>
            <div class="sidebar-brand-text mx-3">manager <sup>Admin</sup></div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'manager:index' %}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading">
            manager
        </div>

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                aria-expanded="true" aria-controls="collapseTwo">
                <i class="fas fa-fw fa-cog"></i>
                <span>Payments</span>
            </a>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            </div>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

<!--        &lt;!&ndash; Heading &ndash;&gt;-->
<!--        <div class="sidebar-heading">-->
<!--            Addons-->
<!--        </div>-->

<!--        &lt;!&ndash; Nav Item - Pages Collapse Menu &ndash;&gt;-->
<!--        <li class="nav-item">-->
<!--            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"-->
<!--                aria-expanded="true" aria-controls="collapsePages">-->
<!--                <i class="fas fa-fw fa-folder"></i>-->
<!--                <span>Pages</span>-->
<!--            </a>-->
<!--            <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">-->
<!--                <div class="bg-white py-2 collapse-inner rounded">-->
<!--                    <h6 class="collapse-header">Login Screens:</h6>-->
<!--                    <a class="collapse-item" href="#">Login</a>-->
<!--                </div>-->
<!--            </div>-->
<!--        </li>-->

<!--        &lt;!&ndash; Nav Item - Charts &ndash;&gt;-->
<!--        <li class="nav-item">-->
<!--            <a class="nav-link" href="#">-->
<!--                <i class="fas fa-fw fa-chart-area"></i>-->
<!--                <span>Charts</span></a>-->
<!--        </li>-->

<!--        &lt;!&ndash; Nav Item - Tables &ndash;&gt;-->
<!--        <li class="nav-item">-->
<!--            <a class="nav-link" href="#">-->
<!--                <i class="fas fa-fw fa-table"></i>-->
<!--                <span>Tables</span></a>-->
<!--        </li>-->

        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

<!--        &lt;!&ndash; Sidebar Message &ndash;&gt;-->
<!--        <div class="sidebar-card d-none d-lg-flex">-->
<!--            <img class="sidebar-card-illustration mb-2" src="img/undraw_rocket.svg" alt="...">-->
<!--            <p class="text-center mb-2"><strong>SB Admin Pro</strong> is packed with premium features, components, and more!</p>-->
<!--            <a class="btn btn-success btn-sm" href="https://startbootstrap.com/theme/sb-admin-pro">Upgrade to Pro!</a>-->
<!--        </div>-->

    </ul>
    <!-- End of Sidebar -->

Airport-Management-System-master/manager/templates/manager/includes/top-bar.html
{% load static %}
<!-- Topbar -->
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search -->
        <form
            class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
                <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                    aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                    </button>
                </div>
            </div>
        </form>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
                <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-search fa-fw"></i>
                </a>
                <!-- Dropdown - Messages -->
                <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                    aria-labelledby="searchDropdown">
                    <form class="form-inline mr-auto w-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small"
                                placeholder="Search for..." aria-label="Search"
                                aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user.get_full_name}}</span>
                    {% if request.user.finance.financeprofile.image.url %}
                        <img class="img-profile rounded-circle" src="{{request.Users.manager.managerprofile.image.url}}">
                    {% else %}
                        <img class="img-profile rounded-circle" src="{% static 'handyman/img/undraw_profile.svg' %}">
                    {% endif %}
                </a>
                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                    aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="{% url 'manager:profile' %}">
                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                        Profile
                    </a>
                    <a class="dropdown-item" href="{% url 'manager:change-password' %}">
                        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                        Change Password
                    </a>
                    <a class="dropdown-item" href="{% url 'manager:feedback' %}">
                        <i class="fas fa-sms fa-sm fa-fw mr-2 text-gray-400"></i>
                        Feedback
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Logout
                    </a>
                </div>
            </li>

        </ul>

    </nav>
    <!-- End of Topbar -->